[unique]
id = "serpent_stare"
name = "Serpant Stare"
base_type = "silk_hood"
flavor = "The eyes that peer back through the grass are not always your friend."

[[unique.mods]]
stat = "chaos_resistance"
min = 40
max = 60

[[unique.mods]]
stat = "increased_attack_speed"
min = 15
max = 25

[[unique.mods]]
stat = "increased_poison_duration"
min = 30
max = 100

[[recipe.required_affixes]]
stat = "added_dexterity"
affix_type = "suffix"
min_tier = 1
max_tier = 1

[[recipe.required_affixes]]
stat = "added_intelligence"
affix_type = "suffix"
min_tier = 1
max_tier = 1

[[recipe.required_affixes]]
stat = "increased_evasion"
affix_type = "prefix"
min_tier = 1
max_tier = 99

[[recipe.mappings]]
from_stat = "added_dexterity"
to_mod_index = 1
mode = "percentage"
influence = 1.0

[[recipe.mappings]]
from_stat = "added_intelligence"
to_mod_index = 2
mode = "percentage"
influence = 1.0

[[recipe.mappings]]
from_stat = "added_dexterity"
to_mod_index = 0
mode = "direct"
influence = 1.0
