[[currencies]]
id = "life_blessing"
name = "Vitality Blessing"
description = "Adds maximum life to armour (guaranteed T1)"
category = "Defense"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_life"
tier = 1
weight = 100

[[currencies]]
id = "lightning_enchant"
name = "Storm Crystal"
description = "Adds lightning damage to a weapon"
category = "Elemental"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_lightning_damage"
weight = 100

[[currencies]]
id = "cold_enchant"
name = "Frost Crystal"
description = "Adds cold damage to a weapon"
category = "Elemental"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_cold_damage"
weight = 100

[[currencies]]
id = "speed_enchant"
name = "Quicksilver Rune"
description = "Adds movement speed to boots"
category = "Defense"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "increased_movement_speed"
weight = 100

[[currencies]]
id = "elemental_ward"
name = "Warding Rune"
description = "Adds a random elemental resistance"
category = "Defense"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "fire_resistance"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "cold_resistance"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "lightning_resistance"
weight = 100

[[currencies]]
id = "elemental_enchant"
name = "Prismatic Crystal"
description = "Adds random elemental damage to a weapon"
category = "Elemental"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_fire_damage"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "added_cold_damage"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "added_lightning_damage"
weight = 100

[[currencies]]
id = "mostly_fire_enchant"
name = "Volcanic Crystal"
description = "Adds elemental damage (usually fire)"
category = "Elemental"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_fire_damage"
weight = 300

[[currencies.effects.add_specific_affix]]
id = "added_cold_damage"
weight = 50

[[currencies.effects.add_specific_affix]]
id = "added_lightning_damage"
weight = 50

[[currencies]]
id = "attribute_blessing"
name = "Attribute Blessing"
description = "Adds a random attribute to armour"
category = "Defense"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_strength"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "added_dexterity"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "added_intelligence"
weight = 100

[[currencies.effects.add_specific_affix]]
id = "added_accuracy"
weight = 10

[[currencies]]
id = "fire_enchant"
name = "Ember Crystal"
description = "Adds fire damage to a weapon"
category = "Elemental"

[currencies.requires]
rarities = [
    "magic",
    "rare",
]
has_affix = false
has_affix_slot = true

[currencies.effects]
clear_affixes = false
try_unique = false
affix_pools = []

[[currencies.effects.add_specific_affix]]
id = "added_fire_damage"
weight = 100
