[package]
name = "config_editor"
version.workspace = true
edition.workspace = true

[dependencies]
loot_core.workspace = true
ratatui.workspace = true
crossterm.workspace = true
toml.workspace = true
serde.workspace = true
