[[base_types]]
id = "crystal_wand"
name = "Crystal Wand"
class = "wand"
tags = [
    "caster",
    "ranged",
    "elemental",
]

[base_types.implicit]
stat = "increased_critical_chance"
min = 10
max = 20

[base_types.damage]
attack_speed = 1.5
critical_chance = 8.0
spell_efficiency = 100.0

[[base_types.damage.damages]]
type = "cold"
min = 3
max = 8

[[base_types.damage.damages]]
type = "lightning"
min = 1
max = 12

[base_types.requirements]
level = 20
strength = 0
dexterity = 0
constitution = 0
intelligence = 40
wisdom = 0
charisma = 0

[[base_types]]
id = "iron_sword"
name = "Iron Sword"
class = "one_hand_sword"
tags = [
    "melee",
    "physical",
    "attack",
    "sword",
]

[base_types.implicit]
stat = "added_accuracy"
min = 10
max = 20

[base_types.damage]
attack_speed = 1.2999999523162842
critical_chance = 5.0
spell_efficiency = 0.0

[[base_types.damage.damages]]
type = "physical"
min = 5
max = 12

[base_types.requirements]
level = 1
strength = 10
dexterity = 0
constitution = 0
intelligence = 0
wisdom = 0
charisma = 0

[[base_types]]
id = "broad_axe"
name = "Broad Axe"
class = "two_hand_axe"
tags = [
    "melee",
    "physical",
    "attack",
    "axe",
]

[base_types.damage]
attack_speed = 1.0
critical_chance = 5.0
spell_efficiency = 0.0

[[base_types.damage.damages]]
type = "physical"
min = 25
max = 55

[base_types.requirements]
level = 15
strength = 40
dexterity = 0
constitution = 0
intelligence = 0
wisdom = 0
charisma = 0

[[base_types]]
id = "hunting_bow"
name = "Hunting Bow"
class = "bow"
tags = [
    "ranged",
    "physical",
    "attack",
    "bow",
]

[base_types.implicit]
stat = "added_accuracy"
min = 15
max = 30

[base_types.damage]
attack_speed = 1.399999976158142
critical_chance = 5.0
spell_efficiency = 0.0

[[base_types.damage.damages]]
type = "physical"
min = 8
max = 18

[base_types.requirements]
level = 5
strength = 0
dexterity = 20
constitution = 0
intelligence = 0
wisdom = 0
charisma = 0

[[base_types]]
id = "dragon_staff"
name = "Dragon Staff"
class = "staff"
tags = [
    "caster",
    "ranged",
    "fire",
]

[base_types.implicit]
stat = "fire_resistance"
min = 5
max = 15

[base_types.defenses.energy_shield]
min = 12
max = 20

[base_types.damage]
attack_speed = 1.399999976158142
critical_chance = 4.0
spell_efficiency = 120.0

[[base_types.damage.damages]]
type = "fire"
min = 10
max = 20

[base_types.requirements]
level = 45
strength = 10
dexterity = 15
constitution = 0
intelligence = 65
wisdom = 0
charisma = 0

[[base_types]]
id = "infernal_sceptre"
name = "Infernal Sceptre"
class = "one_hand_mace"
tags = [
    "caster",
    "melee",
    "fire",
]

[base_types.implicit]
stat = "fire_resistance"
min = 15
max = 25

[base_types.damage]
attack_speed = 1.2000000476837158
critical_chance = 6.0
spell_efficiency = 80.0

[[base_types.damage.damages]]
type = "physical"
min = 5
max = 10

[[base_types.damage.damages]]
type = "fire"
min = 8
max = 16

[base_types.requirements]
level = 30
strength = 20
dexterity = 0
constitution = 0
intelligence = 35
wisdom = 0
charisma = 0

[[base_types]]
id = "butt_cannon"
name = "Butt Cannon"
class = "bow"
tags = [
    "ranged",
    "damage",
    "chaos",
]

[base_types.implicit]
stat = "added_physical_damage"
min = 10
max = 200

[base_types.defenses.armour]
min = 20
max = 45

[base_types.damage]
attack_speed = 0.30000001192092896
critical_chance = 1.0
spell_efficiency = 1.0

[[base_types.damage.damages]]
type = "chaos"
min = 100
max = 150

[[base_types.damage.damages]]
type = "physical"
min = 45
max = 60

[base_types.requirements]
level = 24
strength = 11
dexterity = 20
constitution = 0
intelligence = 13
wisdom = 0
charisma = 0

[[base_types]]
id = "steel_sword"
name = "Steel Sword"
class = "one_hand_sword"
tags = [
    "melee",
    "physical",
    "attack",
    "sword",
]

[base_types.implicit]
stat = "added_accuracy"
min = 20
max = 40

[base_types.damage]
attack_speed = 1.2999999523162842
critical_chance = 5.0
spell_efficiency = 0.0

[[base_types.damage.damages]]
type = "physical"
min = 12
max = 28

[base_types.requirements]
level = 10
strength = 25
dexterity = 0
constitution = 0
intelligence = 0
wisdom = 0
charisma = 0
