# Poison Affix Pool - Exclusive affixes only available through special currencies

[[pools]]
id = "poison"
name = "Poison Affixes"
description = "Toxic affixes that can only be obtained through special means"
affixes = [
    "poison_damage_flat",
    "poison_damage_percent",
    "poison_damage_over_time",
    "chance_to_poison",
    "poison_duration",
    "chaos_resist",
]
